[[Qt6Positioning]]
arch = "aarch64"
git-tree-sha1 = "75cf0156a0d9c02332671d1aaee9f29ed64b19cb"
os = "macos"

    [[Qt6Positioning.download]]
    sha256 = "b2abd58f267310662155ed364021965d449eb5d577a55bd7a51ebd8df34a9dae"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.aarch64-apple-darwin.tar.gz"
[[Qt6Positioning]]
arch = "x86_64"
git-tree-sha1 = "fbe724f05e0cfeebb70131f8c1f5a27d7a4cbeb0"
os = "macos"

    [[Qt6Positioning.download]]
    sha256 = "4ebe1d15ed6265655f33c379dd812bc669f201c16365cc64670b25eb7cd811da"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.x86_64-apple-darwin.tar.gz"
[[Qt6Positioning]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9d30af057aa5425ed5443caf1488e719f5749d7"
os = "windows"

    [[Qt6Positioning.download]]
    sha256 = "a8c34f10393173ad4bbed181eb0270e3f88d86203d4186c46419d37812113186"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25d622eadeb86167a24ae0284e010fd5f81b1af7"
os = "windows"

    [[Qt6Positioning.download]]
    sha256 = "5f0699603ab126046760f6504a1aef33116234e33ab1f9d687cb930814bb195f"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22de78c11c7bd89383567b1ae75d0a13661c822c"
libc = "glibc"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "f5311d92351f758057542b6e3dce2bbb72cae4fccb3e94031c1f71e9f8d380e4"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef7030686a02a84da702902016fb3ef3ca8170e1"
libc = "musl"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "b78d904adb64e669f779474aaf0e767f7fdbe303bf2c1c5ff5a7002b5235543d"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a0fb867b7a6175692b475f6b8fbf3369543c1ab"
libc = "glibc"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "9b55740d24ece27608c1e640bb6cb05acb431d451533a1160225827f25d62749"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52a533466db3566b99b009713e10bd61b939d356"
libc = "musl"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "2bb837d037d0c0bcb1f2b9940fedb8427192d77f2d25aa823d3db7401b94918d"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "570e1cd1f1e55b75a4e8c1533d38e47652a691df"
libc = "glibc"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "981f9a4ef40c0ff2c0c7e9c108686ffdf9e5732393525bdd7af2b04ae70320f1"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7e60712bf7c7db43d4086de4d9df1f9ce4a1ca0"
libc = "musl"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "b8fbcd2bc94b4276d7776de068c873980143d28c50f907c79c455a78c9254bfd"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.i686-linux-musl-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36edefa53a4b92d742a426fb317eb20998316588"
libc = "glibc"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "c1800619a8029dae5645ff36010a4fd25d9ee4c0c4f5c4b084686d50a8a6f5b4"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89fff7bd38f8ea16c2921c613ff9b5b37c1bce18"
libc = "glibc"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "ce48f8f4d4c3a9d11413ce56cab2a9f05ee9582486b64ed42968e04b8466aa92"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "587343987493995d4a209fb17a62b0f23ff224fc"
libc = "musl"
os = "linux"

    [[Qt6Positioning.download]]
    sha256 = "e428e875706f9150a6b5b7d0bf9df1ae06b24d049778f2b06f49e8410e05c3f7"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6Positioning]]
arch = "x86_64"
git-tree-sha1 = "946fa5e05eec250a42a683c8aad04d98c0885724"
os = "freebsd"

    [[Qt6Positioning.download]]
    sha256 = "76e1d21bcc46840ecf9713973137f832dc31cb7c497cd64a6b9192dbcbd84dcb"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Positioning_jll.jl/releases/download/Qt6Positioning-v6.8.2+0/Qt6Positioning.v6.8.2.x86_64-unknown-freebsd.tar.gz"
